# This file has been autogenerated. Do not change by hand. 

#' Create parameter object for the function getDbCohortMethodData
#'
#' @details
#' Create an object defining the parameter values. To be used in the
#' \code{\link{createCohortMethodAnalysis}} function.
#'
#' @param washoutWindow                             The mininum required continuous observation time
#'                                                  prior to indexdate for a person to be included in
#'                                                  the cohort.
#' @param indicationLookbackWindow                  The window to look back prior to cohort index date
#'                                                  to identifyrecords of a indication condition.  Only
#'                                                  applicable ifindicationConceptIds != ”.
#' @param studyStartDate                            A calendar date specifying the minimum date that a
#'                                                  cohort indexdate can appear. Date format is
#'                                                  'yyyymmdd'.
#' @param studyEndDate                              A calendar date specifying the maximum date that a
#'                                                  cohort indexdate can appear. Date format is
#'                                                  'yyyymmdd'.
#' @param outcomeConditionTypeConceptIds            A list of TYPE_CONCEPT_ID values that will
#'                                                  restrictcondition occurrences.  Only applicable if
#'                                                  outcomeTable =CONDITION_OCCURRENCE.
#' @param excludeDrugsFromCovariates                Should the target and comparator drugs (and their
#'                                                  descendantconcepts) be excluded from the
#'                                                  covariates? Note that this willwork if the drugs
#'                                                  are actualy drug concept IDs (and not cohortIDs).
#' @param useCovariateDemographics                  A boolean value (TRUE/FALSE) to determine
#'                                                  ifdemographic covariates (age in 5-yr
#'                                                  increments,gender, race, ethnicity, year of index
#'                                                  date, monthof index date) will be created and
#'                                                  included infuture models.
#' @param useCovariateDemographicsGender            A boolean value (TRUE/FALSE) to determine if
#'                                                  gendershould be included in the model.
#' @param useCovariateDemographicsRace              A boolean value (TRUE/FALSE) to determine if
#'                                                  raceshould be included in the model.
#' @param useCovariateDemographicsEthnicity         A boolean value (TRUE/FALSE) to determine
#'                                                  ifethnicity should be included in the model.
#' @param useCovariateDemographicsAge               A boolean value (TRUE/FALSE) to determine if age(in
#'                                                  5 year increments) should be included in themodel.
#' @param useCovariateDemographicsYear              A boolean value (TRUE/FALSE) to determine
#'                                                  ifcalendar year should be included in the model.
#' @param useCovariateDemographicsMonth             A boolean value (TRUE/FALSE) to determine
#'                                                  ifcalendar month should be included in the model.
#' @param useCovariateConditionOccurrence           A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates derived from CONDITION_OCCURRENCE
#'                                                  tablewill be created and included in future models.
#' @param useCovariateConditionOccurrence365d       A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates will be created and used in models
#'                                                  thatlook for presence/absence of condition in
#'                                                  365dwindow prior to or on cohort index date.
#'                                                  Onlyapplicable if useCovariateConditionOccurrence
#'                                                  =TRUE.
#' @param useCovariateConditionOccurrence30d        A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates will be created and used in models
#'                                                  thatlook for presence/absence of condition in
#'                                                  30dwindow prior to or on cohort index date.
#'                                                  Onlyapplicable if useCovariateConditionOccurrence
#'                                                  =TRUE.
#' @param useCovariateConditionOccurrenceInpt180d   A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates will be created and used in models
#'                                                  thatlook for presence/absence of condition
#'                                                  withininpatient type in 180d window prior to or on
#'                                                  cohortindex date.  Only applicable
#'                                                  ifuseCovariateConditionOccurrence = TRUE.
#' @param useCovariateConditionEra                  A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates derived from CONDITION_ERA table will
#'                                                  becreated and included in future models.
#' @param useCovariateConditionEraEver              A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates will be created and used in models
#'                                                  thatlook for presence/absence of condition era
#'                                                  anytimeprior to or on cohort index date.  Only
#'                                                  applicableif useCovariateConditionEra = TRUE.
#' @param useCovariateConditionEraOverlap           A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates will be created and used in models
#'                                                  thatlook for presence/absence of condition era
#'                                                  thatoverlaps the cohort index date.  Only
#'                                                  applicable ifuseCovariateConditionEra = TRUE.
#' @param useCovariateConditionGroup                A boolean value (TRUE/FALSE) to determine if
#'                                                  allCONDITION_OCCURRENCE and CONDITION_ERA
#'                                                  covariatesshould be aggregated or rolled-up to
#'                                                  higher-levelconcepts based on vocabluary
#'                                                  classification.
#' @param useCovariateConditionGroupMeddra          A boolean value (TRUE/FALSE) to determine if
#'                                                  allCONDITION_OCCURRENCE and CONDITION_ERA
#'                                                  covariatesshould be aggregated or rolled-up to
#'                                                  higher-levelconcepts based on the MEDDRA
#'                                                  classification.
#' @param useCovariateConditionGroupSnomed          A boolean value (TRUE/FALSE) to determine if
#'                                                  allCONDITION_OCCURRENCE and CONDITION_ERA
#'                                                  covariatesshould be aggregated or rolled-up to
#'                                                  higher-levelconcepts based on the SNOMED
#'                                                  classification.
#' @param useCovariateDrugExposure                  A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates derived from DRUG_EXPOSURE table will
#'                                                  becreated and included in future models.
#' @param useCovariateDrugExposure365d              A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates will be created and used in models
#'                                                  thatlook for presence/absence of drug in 365d
#'                                                  windowprior to or on cohort index date.  Only
#'                                                  applicableif useCovariateDrugExposure = TRUE.
#' @param useCovariateDrugExposure30d               A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates will be created and used in models
#'                                                  thatlook for presence/absence of drug in 30d
#'                                                  windowprior to or on cohort index date.  Only
#'                                                  applicableif useCovariateDrugExposure = TRUE.
#' @param useCovariateDrugEra                       A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates derived from DRUG_ERA table will
#'                                                  becreated and included in future models.
#' @param useCovariateDrugEra365d                   A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates will be created and used in models
#'                                                  thatlook for presence/absence of drug era in
#'                                                  365dwindow prior to or on cohort index date.
#'                                                  Onlyapplicable if useCovariateDrugEra = TRUE.
#' @param useCovariateDrugEra30d                    A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates will be created and used in models
#'                                                  thatlook for presence/absence of drug era in 30d
#'                                                  windowprior to or on cohort index date.  Only
#'                                                  applicableif useCovariateDrugEra = TRUE.
#' @param useCovariateDrugEraOverlap                A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates will be created and used in models
#'                                                  thatlook for presence/absence of drug era that
#'                                                  overlapsthe cohort index date.  Only applicable
#'                                                  ifuseCovariateDrugEra = TRUE.
#' @param useCovariateDrugEraEver                   A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates will be created and used in models
#'                                                  thatlook for presence/absence of drug era anytime
#'                                                  priorto or on cohort index date.  Only applicable
#'                                                  ifuseCovariateDrugEra = TRUE.
#' @param useCovariateDrugGroup                     A boolean value (TRUE/FALSE) to determine if
#'                                                  allDRUG_EXPOSURE and DRUG_ERA covariates should
#'                                                  beaggregated or rolled-up to higher-level concepts
#'                                                  ofdrug classes based on vocabluary classification.
#' @param useCovariateProcedureOccurrence           A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates derived from PROCEDURE_OCCURRENCE
#'                                                  tablewill be created and included in future models.
#' @param useCovariateProcedureOccurrence365d       A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates will be created and used in models
#'                                                  thatlook for presence/absence of procedure in
#'                                                  365dwindow prior to or on cohort index date.
#'                                                  Onlyapplicable if useCovariateProcedureOccurrence
#'                                                  =TRUE.
#' @param useCovariateProcedureOccurrence30d        A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates will be created and used in models
#'                                                  thatlook for presence/absence of procedure in
#'                                                  30dwindow prior to or on cohort index date.
#'                                                  Onlyapplicable if useCovariateProcedureOccurrence
#'                                                  =TRUE.
#' @param useCovariateProcedureGroup                A boolean value (TRUE/FALSE) to determine if
#'                                                  allPROCEDURE_OCCURRENCE covariates should
#'                                                  beaggregated or rolled-up to higher-level
#'                                                  conceptsbased on vocabluary classification.
#' @param useCovariateObservation                   A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates derived from OBSERVATION table will
#'                                                  becreated and included in future models.
#' @param useCovariateObservation365d               A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates will be created and used in models
#'                                                  thatlook for presence/absence of observation in
#'                                                  365dwindow prior to or on cohort index date.
#'                                                  Onlyapplicable if useCovariateObservation = TRUE.
#' @param useCovariateObservation30d                A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates will be created and used in models
#'                                                  thatlook for presence/absence of observation in
#'                                                  30dwindow prior to or on cohort index date.
#'                                                  Onlyapplicable if useCovariateObservation = TRUE.
#' @param useCovariateObservationBelow              A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates will be created and used in models
#'                                                  thatlook for presence/absence of observation with
#'                                                  anumeric value below normal range for latest
#'                                                  valuewithin 180d of cohort index.  Only applicable
#'                                                  ifuseCovariateObservation = TRUE.
#' @param useCovariateObservationAbove              A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates will be created and used in models
#'                                                  thatlook for presence/absence of observation with
#'                                                  anumeric value above normal range for latest
#'                                                  valuewithin 180d of cohort index.  Only applicable
#'                                                  ifuseCovariateObservation = TRUE.
#' @param useCovariateObservationCount365d          A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates will be created and used in models
#'                                                  thatlook for the count of each observation concept
#'                                                  in365d window prior to or on cohort index date.
#'                                                  Onlyapplicable if useCovariateObservation = TRUE.
#' @param useCovariateConceptCounts                 A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates will be created and used in models
#'                                                  thatcount the number of concepts that a person
#'                                                  haswithin each domain (CONDITION, DRUG,
#'                                                  PROCEDURE,OBSERVATION)
#' @param useCovariateRiskScores                    A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates will be created and used in models
#'                                                  thatcalculate various Risk Scores, including
#'                                                  Charlson,DCSI.
#' @param useCovariateRiskScoresCharlson            A boolean value (TRUE/FALSE) to determine if
#'                                                  theCharlson comorbidity index should be included
#'                                                  inthe model.
#' @param useCovariateRiskScoresDCSI                A boolean value (TRUE/FALSE) to determine if
#'                                                  theDCSI score should be included in the model.
#' @param useCovariateRiskScoresCHADS2              A boolean value (TRUE/FALSE) to determine if
#'                                                  theCHADS2 score should be included in the model.
#' @param useCovariateInteractionYear               A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates will be created and used in models
#'                                                  thatrepresent interaction terms between all
#'                                                  othercovariates and the year of the cohort index
#'                                                  date.
#' @param useCovariateInteractionMonth              A boolean value (TRUE/FALSE) to determine
#'                                                  ifcovariates will be created and used in models
#'                                                  thatrepresent interaction terms between all
#'                                                  othercovariates and the month of the cohort index
#'                                                  date.
#' @param excludedCovariateConceptIds               A list of concept IDs that should NOT be used
#'                                                  toconstruct covariates.
#' @param includedCovariateConceptIds               A list of concept IDs that should be used
#'                                                  toconstruct covariates.
#' @param deleteCovariatesSmallCount                A numeric value used to remove covariates thatoccur
#'                                                  in both cohorts fewer
#'                                                  thandeleteCovariateSmallCounts time.
#'
#' @export
createGetDbCohortMethodDataArgs <- function(washoutWindow = 183,
                                            indicationLookbackWindow = 183,
                                            studyStartDate = "",
                                            studyEndDate = "",
                                            outcomeConditionTypeConceptIds = c(),
                                            excludeDrugsFromCovariates = TRUE,
                                            useCovariateDemographics = TRUE,
                                            useCovariateDemographicsGender = TRUE,
                                            useCovariateDemographicsRace = TRUE,
                                            useCovariateDemographicsEthnicity = TRUE,
                                            useCovariateDemographicsAge = TRUE,
                                            useCovariateDemographicsYear = TRUE,
                                            useCovariateDemographicsMonth = TRUE,
                                            useCovariateConditionOccurrence = TRUE,
                                            useCovariateConditionOccurrence365d = TRUE,
                                            useCovariateConditionOccurrence30d = TRUE,
                                            useCovariateConditionOccurrenceInpt180d = TRUE,
                                            useCovariateConditionEra = FALSE,
                                            useCovariateConditionEraEver = FALSE,
                                            useCovariateConditionEraOverlap = FALSE,
                                            useCovariateConditionGroup = FALSE,
                                            useCovariateConditionGroupMeddra = FALSE,
                                            useCovariateConditionGroupSnomed = FALSE,
                                            useCovariateDrugExposure = FALSE,
                                            useCovariateDrugExposure365d = FALSE,
                                            useCovariateDrugExposure30d = FALSE,
                                            useCovariateDrugEra = FALSE,
                                            useCovariateDrugEra365d = FALSE,
                                            useCovariateDrugEra30d = FALSE,
                                            useCovariateDrugEraOverlap = FALSE,
                                            useCovariateDrugEraEver = FALSE,
                                            useCovariateDrugGroup = FALSE,
                                            useCovariateProcedureOccurrence = FALSE,
                                            useCovariateProcedureOccurrence365d = FALSE,
                                            useCovariateProcedureOccurrence30d = FALSE,
                                            useCovariateProcedureGroup = FALSE,
                                            useCovariateObservation = FALSE,
                                            useCovariateObservation365d = FALSE,
                                            useCovariateObservation30d = FALSE,
                                            useCovariateObservationBelow = FALSE,
                                            useCovariateObservationAbove = FALSE,
                                            useCovariateObservationCount365d = FALSE,
                                            useCovariateConceptCounts = FALSE,
                                            useCovariateRiskScores = FALSE,
                                            useCovariateRiskScoresCharlson = FALSE,
                                            useCovariateRiskScoresDCSI = FALSE,
                                            useCovariateRiskScoresCHADS2 = FALSE,
                                            useCovariateInteractionYear = FALSE,
                                            useCovariateInteractionMonth = FALSE,
                                            excludedCovariateConceptIds = c(),
                                            includedCovariateConceptIds = c(),
                                            deleteCovariatesSmallCount = 100) {
  # First: get default values:
  analysis <- list()
  for (name in names(formals(createGetDbCohortMethodDataArgs))) {
    analysis[[name]] <- get(name)
  }
  # Second: overwrite defaults with actual values:
  values <- lapply(as.list(match.call())[-1], function(x) eval(x, envir = sys.frame(-3)))
  for (name in names(values)) {
    if (name %in% names(analysis))
      analysis[[name]] <- values[[name]]
  }
  class(analysis) <- "args"
  return(analysis)
}

#' Create parameter object for the function createPs
#'
#' @details
#' Create an object defining the parameter values. To be used in the
#' \code{\link{createCohortMethodAnalysis}} function.
#'
#' @param excludeCovariateIds   Exclude these covariates from the propensity model.
#' @param prior                 The prior used to fit the model. See createPriorfor details.
#' @param control               The control object used to control the cross-validation used
#'                              todetermine the hyperparameters of the prior (if applicable).
#'                              SeecreateControl for details.
#'
#' @export
createCreatePsArgs <- function(excludeCovariateIds = NULL,
                               prior = createPrior("laplace",
                                                   exclude = c(0),
                                                   useCrossValidation = TRUE),
                               control = createControl(noiseLevel = "silent",
                                                       cvType = "auto",
                                                       startingVariance = 0.1)) {
  # First: get default values:
  analysis <- list()
  for (name in names(formals(createCreatePsArgs))) {
    analysis[[name]] <- get(name)
  }
  # Second: overwrite defaults with actual values:
  values <- lapply(as.list(match.call())[-1], function(x) eval(x, envir = sys.frame(-3)))
  for (name in names(values)) {
    if (name %in% names(analysis))
      analysis[[name]] <- values[[name]]
  }
  class(analysis) <- "args"
  return(analysis)
}

#' Create parameter object for the function trimByPs
#'
#' @details
#' Create an object defining the parameter values. To be used in the
#' \code{\link{createCohortMethodAnalysis}} function.
#'
#' @param trimFraction   This fraction will be removed from each treatment group. In the
#'                       treatmentgroup, persons with the highest propensity scores will be removed, in
#'                       thecomparator group person with the lowest scores will be removed.
#'
#' @export
createTrimByPsArgs <- function(trimFraction = 0.05) {
  # First: get default values:
  analysis <- list()
  for (name in names(formals(createTrimByPsArgs))) {
    analysis[[name]] <- get(name)
  }
  # Second: overwrite defaults with actual values:
  values <- lapply(as.list(match.call())[-1], function(x) eval(x, envir = sys.frame(-3)))
  for (name in names(values)) {
    if (name %in% names(analysis))
      analysis[[name]] <- values[[name]]
  }
  class(analysis) <- "args"
  return(analysis)
}

#' Create parameter object for the function trimByPsToEquipoise
#'
#' @details
#' Create an object defining the parameter values. To be used in the
#' \code{\link{createCohortMethodAnalysis}} function.
#'
#' @param bounds   The upper and lower bound on the preference score for keeping persons
#'
#' @export
createTrimByPsToEquipoiseArgs <- function(bounds = c(0.25, 0.75)) {
  # First: get default values:
  analysis <- list()
  for (name in names(formals(createTrimByPsToEquipoiseArgs))) {
    analysis[[name]] <- get(name)
  }
  # Second: overwrite defaults with actual values:
  values <- lapply(as.list(match.call())[-1], function(x) eval(x, envir = sys.frame(-3)))
  for (name in names(values)) {
    if (name %in% names(analysis))
      analysis[[name]] <- values[[name]]
  }
  class(analysis) <- "args"
  return(analysis)
}

#' Create parameter object for the function matchOnPsAndCovariates
#'
#' @details
#' Create an object defining the parameter values. To be used in the
#' \code{\link{createCohortMethodAnalysis}} function.
#'
#' @param caliper        The caliper for matching. A caliper is the distance which is acceptable forany
#'                       match. Observations which are outside of the caliper are dropped. Acaliper of
#'                       0 means no caliper is used.
#' @param caliperScale   The scale on which the caliper is defined. Two scales
#'                       aresupported:caliperScale = 'propensity score' or caliperScale
#'                       ='standardized'. On the standardized scale, the caliper is interpreted
#'                       instandard deviations of the propensity score distribution.
#' @param maxRatio       The maximum number of persons int the comparator arm to be matched to
#'                       eachperson in the treatment arm. A maxRatio of 0 means no maximum: all
#'                       comparatorswill be assigned to a treated person.
#' @param covariateIds   One or more covariate IDs in the cohortMethodData object on which
#'                       subjectsshould be also matched.
#'
#' @export
createMatchOnPsAndCovariatesArgs <- function(caliper = 0.25,
                                             caliperScale = "standardized",
                                             maxRatio = 1,
                                             covariateIds) {
  # First: get default values:
  analysis <- list()
  for (name in names(formals(createMatchOnPsAndCovariatesArgs))) {
    analysis[[name]] <- get(name)
  }
  # Second: overwrite defaults with actual values:
  values <- lapply(as.list(match.call())[-1], function(x) eval(x, envir = sys.frame(-3)))
  for (name in names(values)) {
    if (name %in% names(analysis))
      analysis[[name]] <- values[[name]]
  }
  class(analysis) <- "args"
  return(analysis)
}

#' Create parameter object for the function stratifyByPsAndCovariates
#'
#' @details
#' Create an object defining the parameter values. To be used in the
#' \code{\link{createCohortMethodAnalysis}} function.
#'
#' @param numberOfStrata   Into how many strata should the propensity score be divided? The
#'                         boundariesof the strata are automatically defined to contain equal numbers
#'                         of treatedpersons.
#' @param covariateIds     One or more covariate IDs in the cohortMethodData object on which
#'                         subjectsshould also be stratified.
#'
#' @export
createStratifyByPsAndCovariatesArgs <- function(numberOfStrata = 5, covariateIds) {
  # First: get default values:
  analysis <- list()
  for (name in names(formals(createStratifyByPsAndCovariatesArgs))) {
    analysis[[name]] <- get(name)
  }
  # Second: overwrite defaults with actual values:
  values <- lapply(as.list(match.call())[-1], function(x) eval(x, envir = sys.frame(-3)))
  for (name in names(values)) {
    if (name %in% names(analysis))
      analysis[[name]] <- values[[name]]
  }
  class(analysis) <- "args"
  return(analysis)
}

#' Create parameter object for the function fitOutcomeModel
#'
#' @details
#' Create an object defining the parameter values. To be used in the
#' \code{\link{createCohortMethodAnalysis}} function.
#'
#' @param stratifiedCox          Specifically for Cox regressions: specify whether to use the
#'                               stratadefined in subPopulation in the analysis. For Poissonregression
#'                               and logistic regression, this is implied in 'clr' and'cpr'.
#' @param riskWindowStart        The start of the risk window (in days) relative to the index data.
#' @param riskWindowEnd          The end of the risk window (in days) relative to the index data (+days
#'                               of exposure if the addExposureDaysToEnd parameter isspecified).
#' @param addExposureDaysToEnd   Add the length of exposure the risk window?
#' @param useCovariates          Whether to use the covariate matrix in the cohortMethodData in the
#'                               outcomemodel.
#' @param fitModel               If false, the model will not be fit, and only summary statistics
#'                               areavailable.
#' @param modelType              The type of model to be fitted. See details for options.
#' @param prior                  The prior used to fit the model. SeecreatePrior for details.
#' @param control                The control object used to control the cross-validation used
#'                               todetermine the hyperparameters of the prior (if applicable).
#'                               SeecreateControl for details.
#'
#' @export
createFitOutcomeModelArgs <- function(stratifiedCox = TRUE,
                                      riskWindowStart = 0,
                                      riskWindowEnd = 9999,
                                      addExposureDaysToEnd = FALSE,
                                      useCovariates = TRUE,
                                      fitModel = TRUE,
                                      modelType = "cox",
                                      prior = createPrior("laplace", useCrossValidation = TRUE),
                                      control = createControl(cvType = "auto",
                                                              startingVariance = 0.1,
                                                              selectorType = "byPid",
                                                              noiseLevel = "quiet")) {
  # First: get default values:
  analysis <- list()
  for (name in names(formals(createFitOutcomeModelArgs))) {
    analysis[[name]] <- get(name)
  }
  # Second: overwrite defaults with actual values:
  values <- lapply(as.list(match.call())[-1], function(x) eval(x, envir = sys.frame(-3)))
  for (name in names(values)) {
    if (name %in% names(analysis))
      analysis[[name]] <- values[[name]]
  }
  class(analysis) <- "args"
  return(analysis)
}
