# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.matchOnPs <- function(propensityScores, treatment, maxRatio, caliper) {
    .Call('CohortMethod_matchOnPs', PACKAGE = 'CohortMethod', propensityScores, treatment, maxRatio, caliper)
}

.aucWithCi <- function(propensityScores, treatment) {
    .Call('CohortMethod_aucWithCi', PACKAGE = 'CohortMethod', propensityScores, treatment)
}

.auc <- function(propensityScores, treatment) {
    .Call('CohortMethod_auc', PACKAGE = 'CohortMethod', propensityScores, treatment)
}

.bySum <- function(ffValues, ffBins) {
    .Call('CohortMethod_bySum', PACKAGE = 'CohortMethod', ffValues, ffBins)
}

.findOutcomePrevalence <- function(sBaseline, sExp, cBaseline, cExp) {
    .Call('CohortMethod_findOutcomePrevalence', PACKAGE = 'CohortMethod', sBaseline, sExp, cBaseline, cExp)
}

.generateEventTimesHelper <- function(value, baseline) {
    .Call('CohortMethod_generateEventTimesHelper', PACKAGE = 'CohortMethod', value, baseline)
}

